### ISSUE TITLE
About the generation of query_prototype(proto_teacher)

### ISSUE THREAD

**Issue by GinPd** [cv516Buaa/SD-AANet#1]
Hi, thank you for your open source work and contribution to FSS, and I would like to know why it is possible to utlilize the groud-truth mask of the query set directly in the meta-learner？

**Comment by cv516Buaa** [comment]
> Hi, thank you for your open source work and contribution to FSS, and I would like to know why it is possible to utlilize the groud-truth mask of the query set directly in the meta-learner？

The query_prototype generated from query mask is only used for supervising the model and will not be applied in testing phase, and the query masks in training set are visible so we can use it as label of final loss and anything we like.
